### ISSUE TITLE
无法生成

### ISSUE THREAD

**Issue by kongoldwant** [mailzwj/cardMaker#1]
你好，请问一下为啥我上传了之后生成不了图片哈，谢谢
![image](https://cloud.githubusercontent.com/assets/17177570/14579490/305bd674-03de-11e6-8ce6-8f24040e2581.png)

**Comment by mailzwj** [comment]
可能是PHP后台报错了，你试着按下面的方法排查：
使用Chrome浏览器打开首页，打开你的浏览器的“开发者工具（F12）”，切换到Network面板，填写名片信息，点击生成名片，Network面板中会出现一个php请求，点击请求，在Response选项下，看后台的输出信息~ @kongoldwant

**Comment by kongoldwant** [comment]
jQuery1110005316784349270165_1460808079799({"card":"./profiles/16Apr2016195946.png"})

**Comment by mailzwj** [comment]
@kongoldwant 确认是否开启PHP的GD库扩展，参考教程：
[PHP如何开启GD库](http://jingyan.baidu.com/article/6766299747b3dc54d51b84be.html)

**Comment by kongoldwant** [comment]
谢谢，不过我服务器装的wdcp的lnmp，探针看gd库是“GD库支持：   bundled (2.1.0 compatible)”
![image](https://cloud.githubusercontent.com/assets/17177570/14594176/23b0beba-0566-11e6-81c2-43534f23e065.png)

**Comment by mailzwj** [comment]
那有可能就是代码兼容性问题了，我记得

``` php
$ext = explode("/", $mime)[1];
```

这种写法在老版本的php中是不支持的，需要分开写

``` php
$mimeArr = explode("/", $mime);
$ext = $mimeArr[1];
```

源码（createCard.php）中有几处，你查找修改一下，看看是否解决问题
如果还不行，就使用IDE逐行调试一下，或者简单的使用echo调试
看看是哪个地方出了问题吧~ @kongoldwant
